/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cotizaciones': typeof CotizacionesRoute
  '/dashboard': typeof DashboardRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cotizaciones'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cotizaciones'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/cotizaciones'
    | '/dashboard'
    | '/inventario'
    | '/login'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CotizacionesRoute: typeof CotizacionesRoute
  DashboardRoute: typeof DashboardRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CotizacionesRoute: CotizacionesRoute,
  DashboardRoute: DashboardRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
